Naive Bayesian Models

Multinomial(X[0:2,0:2....] , y[0,1]), Gaussian(X , y[0,1])

In [2]:
import numpy as np ## Good for computation
import pandas as pd ## Good for data frame
import mglearn ##Extract data, visualization
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
simple_train=['call you tonight',
              'Call me a cab',
              'please call me.. please']

In [4]:
pd.DataFrame(simple_train)

0
0         call you tonight
1            Call me a cab
2  please call me.. please

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
vect=CountVectorizer()

In [8]:
vect.fit(simple_train)

CountVectorizer()

In [9]:
vect.get_feature_names()

['cab', 'call', 'me', 'please', 'tonight', 'you']

In [11]:
simple_train_dtm=vect.transform(simple_train)  ##숫자형태로 바꿈

In [12]:
print(simple_train_dtm) ##compressed Row Matrix(CSR format) == non-zero element 만 저장

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


In [13]:
simple_train_dtm.toarray() 

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [15]:
simple_test = ['Please don\'t call me']

In [16]:
simple_test_dtm=vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [17]:
url = 'https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv'
sms = pd.read_table(url, header=None, names=['label', 'message'])

In [18]:
sms.shape

(5572, 2)

In [19]:
pd.DataFrame(sms)

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [20]:
sms.label

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [21]:
label_num=[]
for label    in sms.label:
    if label =="ham":
        label_num.append(0)
    else:
        label_num.append(1)

In [23]:
sms['label_num']=pd.DataFrame(label_num)

In [24]:
sms['label_num']

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label_num, Length: 5572, dtype: int64

In [25]:
X=sms.message
y=sms.label_num
print(X.shape)
print(y.shape)

(5572,)
(5572,)


In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y,random_state =0)

In [27]:
print(X_train.shape)

(4179,)


In [28]:
print(X_test.shape)

(1393,)


In [29]:
vect=CountVectorizer()
vect.fit(X_train)

CountVectorizer()

In [30]:
X_train_dtm=vect.transform(X_train)
X_test_dtm = vect.transform(X_test)

In [31]:
X_train_dtm.toarray().shape ## sample 수, 단어 수

(4179, 7546)

In [32]:
X_test_dtm.toarray().shape

(1393, 7546)

In [34]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [37]:
%time nb.fit(X_train_dtm,y_train)

Wall time: 314 ms


MultinomialNB()

In [38]:
y_pred_class = nb.predict(X_test_dtm)

y_test(Gold Standar)// y_pred_class(Prediction)

In [39]:
from sklearn import metrics

In [40]:
metrics.accuracy_score(y_test,y_pred_class)

0.9885139985642498

## Confusion matrix

[  TP  FP
   FN  TN ]
 
TP:실제로 1인데. 1을 맞추는 경우

FP: 실제로 0인데. 1이라고 하는 경우

FN: 실제로 1인데, 0이라고 하는경우

TN: 실제로 0인데, 0을 맞추는경우

In [41]:
metrics.confusion_matrix(y_test,y_pred_class)

array([[1206,    2],
       [  14,  171]], dtype=int64)

In [45]:
X_test[(y_pred_class==1)&(y_test==0)] ## FP

4382               Mathews or tait or edwards or anderson
1290    Hey...Great deal...Farm tour 9am to 5pm $95/pa...
Name: message, dtype: object

In [46]:
X_test[(y_pred_class==0)&(y_test==1)] ## FP

684     Hi I'm sue. I am 20 years old and work as a la...
731     Email AlertFrom: Jeri StewartSize: 2KBSubject:...
2575    Your next amazing xxx PICSFREE1 video will be ...
1940    More people are dogging in your area now. Call...
751     Do you realize that in about 40 years, we'll h...
4213    Missed call alert. These numbers called but le...
4298    thesmszone.com lets you send free anonymous an...
3864    Oh my god! I've found your number again! I'm s...
5449    Latest News! Police station toilet stolen, cop...
1430    For sale - arsenal dartboard. Good condition b...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
3460    Not heard from U4 a while. Call me now am here...
2823    ROMCAPspam Everyone around should be respondin...
2402    Babe: U want me dont u baby! Im nasty and have...
Name: message, dtype: object

In [47]:
pd.DataFrame(nb.predict_log_proba(X_test_dtm))

0             1
0     0.000000e+00 -3.379980e+01
1    -3.216631e+00 -4.091563e-02
2    -4.925482e-10 -2.143145e+01
3    -2.531593e-03 -5.980172e+00
4    -6.137254e-07 -1.430372e+01
...            ...           ...
1388 -8.698464e-09 -1.856012e+01
1389 -2.270588e+01 -1.377032e-10
1390 -5.735231e+00 -3.235364e-03
1391 -1.173363e-03 -6.748468e+00
1392 -9.379164e-13 -2.769334e+01

[1393 rows x 2 columns]